### ISSUE TITLE
Code Error while using HMD Taiwan Female Data

### ISSUE THREAD

**Issue by kenzilan** [mpascariu/MortalityForecast#12]
Good evening Mr Pascariu. My name is Kenzi Lamberto from Indonesia.

I am trying to analyze Japanese and Taiwan mortality using this package for my undergraduate thesis. I found some problem while using HMD Taiwan Female Data in some period into the Backtesting and BBackTesting from Mortality Forecast  package.  

For the BackTesting, the errors are as follows.
1. Error in while  (all(round(a,7) == 0 != TRUE) { : missing value where TRUE/FALSE needed.
2.  Error in solve.default(W): system is computationally singular: reciprocal condition number = somenumbers e- numbers

For the BBackTesting, the error is
Error in { : task 1 failed - 'could not find function "do.BackTesting"'

May I know what went wrong and what should I do to fix these? Thank you for your attention and time.

Sincerely,

Kenzi Lamberto

![Screenshot (13)](https://user-images.githubusercontent.com/48265542/109409063-de4a6a80-79c1-11eb-887e-0a638481563e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/48265542/109409064-e0acc480-79c1-11eb-9265-c6b9d15b07fd.png)
![Screenshot (11)](https://user-images.githubusercontent.com/48265542/109409065-e1ddf180-79c1-11eb-85ab-0131ded23bb2.png)
![Screenshot (10)](https://user-images.githubusercontent.com/48265542/109409067-e30f1e80-79c1-11eb-8653-45f74499f8fd.png)

**Comment by mpascariu** [comment]
Hi Kenzi,

Could you send me a reproducible example? Just copy/paste your code here and I will have a look.

Regards,
Marius

**Comment by kenzilan** [comment]
Thank you for replying, Mr Pascariu. I will try to tidy up the code for all the errors that I got. For now, I will post this code that gives the 'all(round)' error first. Thank you once again.

#to be send to github

set.seed(1234)
library(MortalityForecast)
library(MortalityLaws)
library(tidyverse)

load("K:/IPB/1Sem7/1Tugas Akhir/data/HMD_LT_f.Rdata") #female Taiwan and Japan data
HMD <- HMD_LT_f #loading as HMD

#this part follows the journal
doData <- function(H, x, y, pop, type = "dx") {
  dxm <- H$data %>%
    filter(country %in% pop, Year %in% y, Age %in% x) %>%
    select(Year, Age, type) %>%
    spread(key = Year, value = type) %>%
    select(-Age) %>%
    apply(., MARGIN = 2, FUN = as.numeric) %>%
    as.data.frame() %>%
    replace.zeros()
  rownames(dxm) <- x
  return(dxm)
}

input_data <- "dx"
output_data <- "ex"


#backtesting for Taiwan 1980-2000 scenario
x  <- 0:110            # Ages
y1 <- 1980:1999        # Training period
y2 <- 2000:2019        # Validation period
y  <- c(y1, y2)        # entire period
K <- "TWN"         # Country to be analysed

#following procedure
D = doData(HMD, x = x, y = y, pop = K)
D = convertFx(x, D, input_data, "mx")
MM <- c("MEM2","MEM3","MEM4","MEM5", "MEM6")

B_TW_F_5 <- do.BackTesting(data = D,
                           data.B = NULL,
                           x = x,
                           y.fit = y1, 
                           y.for = y2,
                           data.in = "mx",
                           models = MM)  #get error from this part at MEM5, while (all(round(a, 7) == 0) != TRUE) { : missing value where TRUE/FALSE needed

##will try to change the problematic part with while (!is.zero(all(round(a, 7)))), still need more info


##trying the bbacktesting
x  <- 0:110
y  <- 1980:2014
dx <- doData(HMD, x = x, y = y, pop = K)
dx <- convertFx(x, D, input_data, "dx")
M  <- c("MEM4")

BB <- do.BBackTesting(data = dx, x = x, y = y,
                      data.in = "dx", 
                      models = M,
                      strategy = c(20, 20, 1)) #get new error  Error in seq.default(from = max(y) - S[1] - S[2] + 1, to = min(y), by = -1 *  : wrong sign in 'by' argument

**Comment by kenzilan** [comment]
changing the year into 
y1 <- 1978:1997        # Training period 2
y2 <- 1998:2017     #validation period 2

causes Error:
solve.default(W) : 
  system is computationally singular: reciprocal condition number = 9.22284e-17

**Comment by mpascariu** [comment]
Hi @kenzilan,

The issue that you are facing in your examples are given by the failure of the algorithm to converge and reconstruct the distribution once the moments have been projected. This is happening mainly on the prediction intervals. The higher the confidence level the higher the chance of getting weird reconstructed distribution on extremities. For now, as a way to move forward with your example you can decrease or remove the confidence levels as follows: 

```r
B_TW_F_5 <- do.BackTesting(data = D,
                           data.B = NULL,
                           x = x,
                           y.fit = y1,
                           y.for = y2,
                           data.in = "dx",
                           models = MM, 
                           level = 0)   # here is my addition
```

In order to have this issue truly fixed a different implementation of the treatment of the prediction intervals would be needed for the MEM model `predict.MEM()`. 

As you have probably noticed this is an experimental package that i started back in 2018 and never got the chance to finalize it to send it to CRAN. I cannot give any indication on how or when the things here will start to take off again. Thanks for your interest!

**Comment by kenzilan** [comment]
Thank you for your reply and enlightenment Mr Pascariu. I will try to decrease the confidence levels. May I ask you one more question? 

How should I interpret the model coefficients indicated in the picture below? Are those the lambdas of the model or are they other things? Thank you


![image](https://user-images.githubusercontent.com/48265542/109756218-151abd80-7c1a-11eb-85dd-339fab14c187.png)

**Comment by mpascariu** [comment]
Hi Kenzi,

The `MEM` model is based on the extrapolation of the time series of statistical moments (2 to 7). In the current implementation this is done using a random walk. When we calibrate `MEM` in fact we calibrate a multivariable random walk with drift `MRW` over the observed moments. The `coefficients` are in fact the drift parameters in the `MRW` model fitted on the 3 time series (in your case). 

Note that the length of `coefficients` vector is 4 not 3. That is because the first value corresponds to M0 which is always 1 and will never have a drift different form 0.

**Comment by kenzilan** [comment]
Dear Mr Pascariu.

From the bottom of my heart, thank you for your time and attention. It's been a great help for me.
I'll probably ask some questions again in the future :)
